# Etapa de construcción
FROM node:latest as build-stage

RUN apt-get update && apt-get install -y vsftpd


# Configurar vsftpd
RUN mkdir /ftp
RUN useradd -d /ftp ftpuser
RUN echo "ftpuser:password" | chpasswd
RUN chown ftpuser:ftpuser /ftp

# Copiar archivos de la aplicación y configuración
WORKDIR /app
COPY package*.json /app/
RUN npm install
COPY . /app

# Construir la aplicación
RUN npm run build --prod

# Etapa de producción
FROM nginx:latest

# Copiar la configuración personalizada de Nginx
COPY nginx.conf /etc/nginx/nginx.conf

# Copiar archivos compilados de la aplicación
COPY --from=build-stage /app/dist/ftp /usr/share/nginx/html

# Exponer puertos
EXPOSE 80 21

# CMD
#CMD ["nginx", "-g", "daemon off;"]
#CMD service vsftpd start && nginx -g 'daemon off;'
CMD service vsftpd start && nginx -g 'daemon off;'